# Generated by Django 3.2.2 on 2022-05-23 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rename_movie_id_review_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rank',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
